### ISSUE TITLE
min vs minIdle

### ISSUE THREAD

**Issue by mattfysh** [panates/lightning-pool#12]
hey there, thanks for this brilliant library! i'm looking at the options and i guess not understanding the difference between min and minIdle, perhaps I thought all resources were idle if they were in the pool - can they be in other states?

**Comment by erayhanoglu** [comment]
Hi,
The "min" option determines the minimum number of resources in the pool. These resources may be idle or active.
For example, min is 2. Pool starts with 2 idle resources. When you call `acquire` pool does nothing. So you have 2 resources now, 1 active 1 idle. 

The "minIdle" option determines the minimum number of idle resources in the pool. For example, minIdle is 2. Pool starts with 2 idle resources. When you call `acquire`, a new resource is created immediately to keep minimum idle resouce count (2). So you have 3 resources now, 1 active 2 idle.

**Comment by mattfysh** [comment]
Brilliant, thanks for the explanation!
