### ISSUE TITLE
Please allow passing parameters to acquire()

### ISSUE THREAD

**Issue by kapouer** [panates/lightning-pool#13]
This would be awesome. New resources sometimes need their own options.

**Comment by erayhanoglu** [comment]
Hi,

I have released version 4.3.0. You will be able to pass factoryCreateOptions argument to acquire() method. The value of the argument will be passed to second argument of PoolFactory.create method.

But dont forget this. The acquire() method does not create new resources unless necessary, it returns the resources that are available in the pool.

**Comment by kapouer** [comment]
Indeed, I understand now it is by design. The right approach is to create several pools, one for each value of instance options... Maybe it would have been better to not add factoryCreateOptions, then ?

**Comment by erayhanoglu** [comment]
Yes. It would be better not to add factoryCreateOptions. I will remove it in v4.4.0

**Comment by kapouer** [comment]
Sorry for that :(
