### ISSUE TITLE
Pool does not destroy resources unless started

### ISSUE THREAD

**Issue by cressie176** [panates/lightning-pool#14]
Hello,

Firstly, thank you for creating lightning-pool. I've been looking for an alternative to generic-pool for some time. I have however found what I think is a bug.

If I create a pool with a minimum number of resources, and call `pool.close()` before either explicitly starting the pool or acquiring resources, lightning-pool never attempts to destroy those resources.

Here's a script that demonstrates the problem...
```js
const { Pool } = require('lightning-pool');

let i = 1;

const factory = {
  create: async function(opts) {
    console.log('CREATE', i);
    return new Promise((resolve) => {
      resolve(i);
      i++;
    });
  },
  destroy: async function(resource) {
    console.log('DESTROY', resource);
  }
};

const pool = new Pool(factory, { max: 10, min: 2});

// Uncommenting this line works around the bug
// pool.start();

process.on('SIGINT', () => {
  pool.close(() => {
    console.log('CLOSED');
    process.exit(0);
  });
})

// Keep the script alive
setInterval(() => {}, 60000);
```

### Output
```
CREATE 1
CREATE 2
^CCLOSED
```

If I uncomment `pool.start()` the output is as follows...
```
CREATE 1
CREATE 2
^CDESTROY 1
DESTROY 2
CLOSED
```

**Comment by erayhanoglu** [comment]
Hi,
Yes, i saw the problem and committed the fix. v4.9.0 has been released.
Thank you for reporting the issue.

**Comment by cressie176** [comment]
Thank you
