### ISSUE TITLE
Nodejs program never exits even if all connections are released

### ISSUE THREAD

**Issue by lroal** [panates/lightning-pool#3]
My program never exits even after all connections are released and 30 seconds is elapsed.
This will not be a problem in a regular http server, but in a utility program it will be. 
The only way to make it exit, is to call pool.close()

**Comment by erayhanoglu** [comment]
Hi,
Pool has a background house keeper timer. This is why program never exits till pool.stop() is called. It works how it is designed. However, we changed this behaviour.  We published v2.1.1. Keep in touch for any further issues. :wink:

**Comment by lroal** [comment]
Nice !
